---
menus:
- name: Chi sono
  url: "#chi-sono"
- name: Il centro
  url: "#il-centro"
- name: Partners
  url: "#special"
- name: Prodotti
  url: "#special"
- name: Servizi
  url: "#servizi"
- name: Contatti
  url: "#contatti"
certifications:
- name: Diploma BCM Milano
  icon: assets/img/partners/BCM-Milano.jpg
  image: assets/img/partners/docu/DIPLOMA_BCM.jpg
- name: Diploma Pandhys
  icon: assets/img/partners/Pandhys-Mini.jpg
  image: assets/img/partners/docu/DIPLOMA_PANDHYS.jpg
- name: Diploma PNEI
  icon: assets/img/partners/PNEI_1.jpg
  image: assets/img/partners/docu/PNEI_VOL_1-2.jpg
- name: Diploma Crystal Nails
  icon: assets/img/partners/Crystal-Nails.jpg
  image: assets/img/partners/docu/DIPLOMA_CRYSTAL-NAILS.jpg
times:
- name: Lunedì
  morning: "-"
  afternoon: "-"
- name: Martedì
  morning: 09:00 - 12:30
  afternoon: 13:30 - 19:00
- name: Mercoledì
  morning: 09:00 - 12:30
  afternoon: 13:30 - 19:00
- name: Giovedì
  morning: 09:00 - 12:30
  afternoon: 13:30 - 20:00
- name: Venerdì
  morning: 09:00 - 12:30
  afternoon: 13:30 - 19:00
- name: Sabato
  morning: 09:00 - 13:00
  afternoon: "-"
